<a href="https://colab.research.google.com/github/AmrHassanKhalaf/Summer_Training_NLP/blob/main/Sec_5/Task_2/Sec_5_T_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# using gensim, fasttext, glove

In [1]:
data = [
    "machine learning is fun",
    "deep learning improves ai",
    "natural language processing with neural networks",
    "word embeddings capture semantic meaning"
]

In [2]:
pip install gensim

In [4]:
import gensim.downloader as api
word2vec_model=api.load("word2vec-google-news-300")
gloVe_model=api.load("glove-wiki-gigaword-300")
fast_model=api.load("fasttext-wiki-news-subwords-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded
[==================================================] 100.0% 376.1/376.1MB downloaded
[==================================================] 100.0% 958.5/958.4MB downloaded


In [9]:
import nltk
from nltk.corpus import wordnet
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
import numpy as np

# Ensure downloads
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

stop_words = set(stopwords.words("english"))

# Clean and tokenize sentence
def get_filtered_tokens(sentence):
    tokens = word_tokenize(sentence.lower())
    return [token for token in tokens if token.isalpha() and token not in stop_words]

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


In [10]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [11]:
def avr_embeding(text,model):
  tokens=word_tokenize(text)
  word_vectors=[model[word] for word in tokens if word in model]
  if not word_vectors:
    return np
  else:
   return np.mean(word_vectors,axis=0)

In [13]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
# Step 1: Vectorize all sentences
vectorizer = CountVectorizer().fit(data)
vectors = vectorizer.transform(data)

# Step 2: Compute pairwise cosine similarity matrix
similarity_matrix = cosine_similarity(vectors)

# Step 3: Print the matrix
print("Cosine Similarity Matrix:")
for row in similarity_matrix:
    print("\t".join(f"{value:.2f}" for value in row))

Cosine Similarity Matrix:
1.00	0.25	0.00	0.00
0.25	1.00	0.00	0.00
0.00	0.00	1.00	0.00
0.00	0.00	0.00	1.00


gensim

In [14]:
avg_vectors=np.array([avr_embeding(sentence,word2vec_model) for sentence in data])
similarity_matrix=cosine_similarity(avg_vectors)
print(similarity_matrix)

[[0.9999998  0.45016417 0.37918076 0.2623811 ]
 [0.45016417 0.9999998  0.39407733 0.32117078]
 [0.37918076 0.39407733 1.0000002  0.4630655 ]
 [0.2623811  0.32117078 0.4630655  0.99999994]]


GloVe

In [16]:
avg_vectors=np.array([avr_embeding(sentence,gloVe_model) for sentence in data])
similarity_matrix=cosine_similarity(avg_vectors)
print(similarity_matrix)

[[0.99999994 0.6256172  0.5480732  0.35537183]
 [0.6256172  0.99999976 0.49188027 0.3523824 ]
 [0.5480732  0.49188027 1.0000001  0.47376773]
 [0.35537183 0.3523824  0.47376773 0.9999996 ]]


Fasttext

In [18]:
avg_vectors=np.array([avr_embeding(sentence,fast_model) for sentence in data])
similarity_matrix=cosine_similarity(avg_vectors)
print(similarity_matrix)

[[0.9999997  0.6155418  0.6612374  0.64005744]
 [0.6155418  1.         0.58614075 0.61035746]
 [0.6612374  0.58614075 1.0000002  0.7446791 ]
 [0.64005744 0.61035746 0.7446791  0.99999994]]
